apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: itsm-db
  namespace: NAMESPACE
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd
  volumeMode: Filesystem
---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/component: itsm-cronjob
  name: itsm-cronjob
  namespace: NAMESPACE
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/component: itsm-cronjob
            label1: label1
            label2: label2
        spec:
          containers:
            image: IMAGE_REFERENCE
            imagePullPolicy: IfNotPresent
            name: itsm
            resources:
              limits:
                cpu: 500m
                ephemeral-storage: 5Gi
                memory: 256Mi
              requests:
                cpu: 200m
                ephemeral-storage: 5Gi
                memory: 128Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
              privileged: false
              procMount: Default
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              seccompProfile:
                type: RuntimeDefault
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /data
              name: data
          volumes:
          - name: db
            persistentVolumeClaim:
              claimName: itsm-db

