apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: itsm-db
  namespace: NAMESPACE
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: SC_BLOCK
  volumeMode: Filesystem
---
apiVersion: liberty.websphere.ibm.com/v1
kind: WebSphereLibertyApplication
metadata:
  name: itsm
  namespace: NAMESPACE
spec:
  license:
    accept: true
    edition: IBM WebSphere Application Server Liberty Core
    productEntitlementSource: IBM Cloud Pak for Applications
  applicationVersion: v2
  topologySpreadConstraints:
    constraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/instance: zone
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
  securityContext:
    runAsNonRoot: true
    readOnlyRootFilesystem: true
  serviceAccount:
    mountToken: true
  autoscaling:
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 60
  applicationImage: IMAGE_REFERENCE
  expose: true
  manageTLS: true
  replicas: 1
  pullPolicy: Always
  manageLTPA: false
  volumeMounts:
    - mountPath: /opt/ibm/wlp/output/defaultServer
      name: db
    - mountPath:  /opt/ibm/wlp/usr/servers/defaultServer/configDropins/defaults
      name: tmpfs-1 
    - mountPath: /logs
      name: tmpfs-2
    - mountPath: /out
      name: tmpfs-3
    - mountPath: /tmp
      name: tmpfs-4
  volumes:
  - name: db
    persistentVolumeClaim:
      claimName: itsm-db
  - name: tmpfs-1
    emptyDir: {}
  - name: tmpfs-2
    emptyDir: {}
  - name: tmpfs-3
    emptyDir: {}
  - name: tmpfs-4
    emptyDir: {}      
  

  
    
