apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: itsm-ca-issuer
  namespace: NAMESPACE
spec:
  ca:
    secretName: itsm-ca-tls
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: itsm-self-signed
  namespace: NAMESPACE
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: itsm-ca-cert
  namespace: NAMESPACE
spec:
  commonName: ITSM CA
  duration: 8766h0m0s
  isCA: true
  issuerRef:
    name: itsm-self-signed
  secretName: itsm-ca-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: itsm-svc-tls
  namespace: NAMESPACE
spec:
  commonName: itsm.reporter.svc
  dnsNames:
  - itsm.reporter.svc
  - itsm.reporter.svc.cluster.local
  - itsm.reporter
  - itsm
  duration: 2160h0m0s
  issuerRef:
    name: itsm-ca-issuer
  secretName: itsm-svc-tls
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: itsm-db
  namespace: NAMESPACE
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: SC_BLOCK
  volumeMode: Filesystem
---
apiVersion: liberty.websphere.ibm.com/v1
kind: WebSphereLibertyApplication
metadata:
  name: itsm
  namespace: NAMESPACE
spec:
  license:
    accept: true
    edition: IBM WebSphere Application Server Liberty Core
    productEntitlementSource: IBM Cloud Pak for Applications
  applicationVersion: v2
  topologySpreadConstraints:
    constraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/instance: zone
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
  securityContext:
    runAsNonRoot: true
    readOnlyRootFilesystem: false
  serviceAccount:
    mountToken: true
  autoscaling:
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 60
  applicationImage: IMAGE_REFERENCE
  expose: true
  manageTLS: true
  route:
    termination: reencrypt
    certificateSecretRef: itsm-svc-tls
  replicas: 1
  pullPolicy: Always
  manageLTPA: false
  volumeMounts:
    - mountPath: /opt/ibm/wlp/output/defaultServer
      name: tmpfs-1 
    - mountPath: /logs
      name: tmpfs-2
    - mountPath: /out
      name: tmpfs-3
    - mountPath: /tmp
      name: tmpfs-4
    - mountPath: /opt/ibm/wlp/output/defaultServer/db
      name: db
    - mountPath: /opt/ibm/wlp/output/defaultServer/tls
      name: tls
    - mountPath: /config/oidc/oidc.properties
      name: oidc
      subPath: oidc.properties
  volumes:
  - name: db
    persistentVolumeClaim:
      claimName: itsm-db
  - name: tls
    secret:
      defaultMode: 420
      secretName: itsm-svc-tls
  - name: oidc
    secret:
      defaultMode: 420
      secretName: itsm-oidc-properties 
  - name: tmpfs-1
    emptyDir: {}
  - name: tmpfs-2
    emptyDir: {}
  - name: tmpfs-3
    emptyDir: {}
  - name: tmpfs-4
    emptyDir: {}      
